# Duplicate Cleaning Notebook (ID-Level Integrity)

This notebook focuses on resolving **duplicate records based on unique ID constraints**.

### Objectives:
- Detect duplicate IDs
- Investigate conflicting records
- Resolve duplicates using deterministic rules
- Ensure ID uniqueness constraint
- Export cleaned dataset

In [ ]:
%pip install pandas numpy

## Step 1: Load Dataset

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../../data/raw/dog_survey.csv')
df.columns = df.columns.str.strip().str.lower()

df.head()

,id,title,first_name,last_name,email,amount_spent_on_dog_food,dog_size,dog_gender,dog_age,unnamed: 9,unnamed: 10
0,1,Mrs,Frasquito,Dene,fdene0@dell.com,£80.05,S,M,53,NaN,NaN
1,2,Ms,Lawrence,Kardos,lkardos1@diigo.com,£66.30,XL,M,2,NaN,NaN
2,3,Rev,Lanna,Wintersgill,lwintersgill2@domainmarket.com,£25.84,L,F,71,NaN,NaN
3,4,Rev,Richmound,Kimmitt,rkimmitt3@jiathis.com,£50.76,M,M,9,NaN,NaN
4,5,Rev,Valeda,Dallender,vdallender4@theglobeandmail.com,£83.41,XL,F,23,NaN,NaN

## Step 2: Detect Duplicate IDs

In [2]:
# Check duplicate IDs
id_counts = df['id'].value_counts()
duplicate_ids = id_counts[id_counts > 1]

print("Total duplicate IDs:", len(duplicate_ids))
print("\nSample duplicate IDs:")
print(duplicate_ids.head(10))

# Extract full duplicate records
df_dup = df[df['id'].isin(duplicate_ids.index)].sort_values('id')

df_dup

Total duplicate IDs: 3

Sample duplicate IDs:
id
222    7
180    2
237    2
Name: count, dtype: int64

,id,title,first_name,last_name,email,amount_spent_on_dog_food,dog_size,dog_gender,dog_age,unnamed: 9,unnamed: 10
179,180,Mrs,Laughton,Kingsmill,lkingsmill4z@slideshare.net,£20.00,S,Male,5,NaN,NaN
180,180,Mrs,Laughton,Kingsmill,lkingsmill4z@slideshare.net,£20.00,S,Male,5,NaN,NaN
222,222,Mr,Hillary,Fisbey,hfisbey65@marketwatch.com,£67.24,S,F,52,NaN,NaN
223,222,Mr,Hillary,Fisbey,hfisbey65@marketwatch.com,£67.24,S,F,52,NaN,NaN
224,222,Mr,Hillary,Fisbey,hfisbey65@marketwatch.com,£67.24,S,F,52,NaN,NaN
225,222,Mr,Hillary,Fisbey,hfisbey65@marketwatch.com,£67.24,S,F,52,NaN,NaN
226,222,Mr,Hillary,Fisbey,hfisbey65@marketwatch.com,£67.24,S,F,52,NaN,NaN
227,222,Mr,Hillary,Fisbey,hfisbey65@marketwatch.com,£67.24,S,F,52,NaN,NaN
228,222,Mr,Hillary,Fisbey,hfisbey65@marketwatch.com,£67.24,S,F,52,NaN,NaN
243,237,Ms,Penelope,Stubbs,pstubbs6k@businesswire.com,£75.90,M,F,9,NaN,NaN
244,237,Ms,Penelope,Stubbs,pstubbs6k@businesswire.com,£75.90,M,F,9,NaN,NaN

## Step 3: Inspect Conflicts Within Duplicate IDs

In [3]:
# Show conflicting records per ID
for i in duplicate_ids.index[:5]:
    print("\n========================")
    print(f"ID: {i}")
    print(df[df['id'] == i])

========================
ID: 222
      id title first_name last_name                      email  \
222  222    Mr    Hillary    Fisbey  hfisbey65@marketwatch.com
223  222    Mr    Hillary    Fisbey  hfisbey65@marketwatch.com
224  222    Mr    Hillary    Fisbey  hfisbey65@marketwatch.com
225  222    Mr    Hillary    Fisbey  hfisbey65@marketwatch.com
226  222    Mr    Hillary    Fisbey  hfisbey65@marketwatch.com
227  222    Mr    Hillary    Fisbey  hfisbey65@marketwatch.com
228  222    Mr    Hillary    Fisbey  hfisbey65@marketwatch.com

    amount_spent_on_dog_food dog_size dog_gender dog_age  unnamed: 9  \
222                   £67.24        S          F      52         NaN
223                   £67.24        S          F      52         NaN
224                   £67.24        S          F      52         NaN
225                   £67.24        S          F      52         NaN
226                   £67.24        S          F      52         NaN
227                   £67.24        S          F      52         NaN
228                   £67.24        S          F      52         NaN

     unnamed: 10
222          NaN
223          NaN
224          NaN
225          NaN
226          NaN
227          NaN
228          NaN

========================
ID: 180
      id title first_name  last_name                        email  \
179  180   Mrs   Laughton  Kingsmill  lkingsmill4z@slideshare.net
180  180   Mrs   Laughton  Kingsmill  lkingsmill4z@slideshare.net

    amount_spent_on_dog_food dog_size dog_gender dog_age  unnamed: 9  \
179                   £20.00        S       Male       5         NaN
180                   £20.00        S       Male       5         NaN

     unnamed: 10
179          NaN
180          NaN

========================
ID: 237
      id title first_name last_name                       email  \
243  237    Ms   Penelope    Stubbs  pstubbs6k@businesswire.com
244  237    Ms   Penelope    Stubbs  pstubbs6k@businesswire.com

    amount_spent_on_dog_food dog_size dog_gender dog_age  unnamed: 9  \
243                   £75.90        M          F       9         NaN
244                   £75.90        M          F       9         NaN

     unnamed: 10
243          NaN
244          NaN

## Step 4: Resolve Duplicate IDs

In [4]:
# Strategy: keep first occurrence (deterministic)
# Alternative could be: keep last or most complete row

before_rows = len(df)

df = df.drop_duplicates(subset=['id'], keep='first')

after_rows = len(df)

print("Rows before:", before_rows)
print("Rows after:", after_rows)
print("Duplicates removed:", before_rows - after_rows)

Rows before: 308
Rows after: 300
Duplicates removed: 8

## Step 5: Validate ID Uniqueness

In [5]:
assert df['id'].is_unique, "ID still contains duplicates!"

print("ID uniqueness confirmed.")

ID uniqueness confirmed.

## Step 6: Export Cleaned Dataset

In [6]:
output_path = '../../data/processed/duplicates_dog_survey_cleaned.csv'
df.to_csv(output_path, index=False)

print(f"Saved: {output_path}")

Saved: ../../data/processed/duplicates_dog_survey_cleaned.csv